config/routes.rb
Rails.application.routes.draw do
  
  constraints subdomain: 'biblequizhelper' do
    root 'staticpages#index'
    
    resources :grids
  end

end

app/models/grid.rb
class Grid < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/grids_controller.rb
class GridsController < ApplicationController

  def index
    @grids = Grid.all
  end

end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def index
    render layout: false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grids_helper.rb
module GridsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/grids/index.html.erb
<h1>All Grids</h1>

<ol>
  <% @grids.each do |grid| %>
    <li><%= link_to grid, '#' %></li>
  <% end %>
</ol>

app/views/layouts/_banner.html.erb
<section>
	<a name="home"></a>
	<div class="hero-container">
		<div class="hero-overlay">
			<div class="hero-text">
				<h1>BibleQuizHelper</h1>
				<h2>WPA's secret weapon.</h2>
				<div>
					<hr width="50%" style="border-color: rgba(255,255,255,0.5);">
					<p><span class="phone-number">304-602-7268</span></p>
					<span>youngwebking@gmail.com</span>
				</div>
			</div>
		</div>
		
		<div class="hero-image">
			<img src="assets/img/banner.jpg">
		</div>
	</div>
</section>

app/views/layouts/_footer.html.erb
<section id="section-contact">
	<hgroup class="footer-brand">
		<h2><span>BibleQuizHelper</span></h2>
	</hgroup>
	<a name="contact"></a>
	<div class="container-fluidOFF">
		<hgroup class="section-header">
			<h1>CONTACT US</h1>
		</hgroup>
		<div class="section-content section-contact">
			<table class="table table-contact">
				<thead></thead>
				<tbody>
					<tr>
						<td>Email</td>
						<td><a href="mailto:youngwebking@gmail.com">youngwebking@gmail.com</a></td>
					</tr>
					<tr>
						<td>Phone #</td>
						<td>304-602-7268</td>
					</tr>
					<tr>
						<td>Address</td>
						<td>201 Fenelton Rd.<br>Fenelton, PA 16034</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</section>

app/views/layouts/_header.html.erb
<header>
	<div class="brand">
		<nav class="navbar navbar-black">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					  <span class="sr-only">Toggle navigation</span>
					  <span class="icon-bar"></span>
					  <span class="icon-bar"></span>
					  <span class="icon-bar"></span>
					</button>
					<%= link_to 'BibleQuizHelper', root_url, class: 'navbar-brand' %>
				</div>
				
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li><%= link_to 'About', '#about' %></li>
						<li><%= link_to 'Contact', '#contact' %></li>
					</ul>
				</div>
			</div>
		</nav>
		<script type="text/javascript">
			$('.nav a').on('click', function(){
					$('.btn-navbar').click(); //bootstrap 2.x
					$('.navbar-toggle').click() //bootstrap 3.x by Richard
			});
		</script>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biblequizhelper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <%= render 'layouts/header' %>
  
  <%= yield %>
  
  <%= render 'layouts/footer' %>

</body>
</html>

app/views/staticpages/_about.html.erb
<section id="section-about">
	<a name="about"></a>
	<div class="container-fluid section-container">
		<hgroup class="section-header">
			<h1>ABOUT US</h1>
		</hgroup>
		<div class="section-content container">
			
<p>BibleQuizHelper is run by my brother, Drew, and I (Brant). Both of us have a passion for both building up God's kingdom and for computer programming. We're called as Christians to use our gifts and talents for the advancement of the Kingdom and for building up the body of Christ.</p>

<p class="paragraph-text">My quizzing coaches spent countless hours creating study lists, grids, and other resources for our team. One day, I realized that I could use my computer programming skills to build software that would generate these study materials on it's own. My hope is that this software will be able to save coaches a lot of time as they put together study materials for their quizzers.</p>

<p class="paragraph-text">We hope our site and its tools will aid you as you strive to deeply ingrain God's Word on your heart!</p>

<p>Grace and peace,<br>
Brant Meier<br>
BibleQuizHelper<br>
Phone: 304-602-7268<br>
Email: <a href="mailto:youngwebking@gmail.com">youngwebking@gmail.com</a></p>

		</div>
	</div>
</section>

app/views/staticpages/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biblequizhelper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
	<%= render 'layouts/header' %>
	
	<section>
		<%= render 'layouts/banner' %>
		
		<section id="section-resources">
			<a name="resources"></a>
			<div class="container-fluid section-container">
				<hgroup class="section-header">
					<h1>RESOURCES</h1>
				</hgroup>
				<div class="section-content container">
          <ol>
            <li><%= link_to 'Grids', grids_path %></li>
          </ol>
        </div>
      </div>
    </section>
			
		<%= render 'staticpages/about' %>

    <%= render 'layouts/footer' %>
	</section>
</body>
</html>